name       : scons
version    : 2.3.5
release    : 1
source     :
    - http://prdownloads.sourceforge.net/scons/scons-2.3.5.tar.gz : 5b72f959cafbef81f408b503bc8e8d5cfc39f41fb5b629e9ff13bdf20a3eefe2
license    : MIT
summary    : Extensible Python-based build utility
description: |
    Extensible Python-based build utility
builddeps  :
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
