name       : scons
version    : 3.0.2
release    : 4
source     :
    - https://vorboss.dl.sourceforge.net/project/scons/scons/3.0.2/scons-3.0.2.tar.gz : d0afcf8f4c2ea5fa7af3c9321c0cb3ea1c83d137196be10c4cb2c79cc5dade01
license    : MIT
component  : programming.tools
summary    : Extensible Python-based build utility
description: |
    Extensible Python-based build utility
build      : |
    %python3_setup
install    : |
    %python3_install
