name       : scons
version    : 2.5.1
release    : 2
source     :
    - http://prdownloads.sourceforge.net/scons/scons-2.5.1.tar.gz : 0b25218ae7b46a967db42f2a53721645b3d42874a65f9552ad16ce26d30f51f2
license    : MIT
component  : programming.tools
summary    : Extensible Python-based build utility
description: |
    Extensible Python-based build utility
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install