name       : scons
version    : 3.1.1
release    : 5
source     :
    - https://vorboss.dl.sourceforge.net/project/scons/scons/3.1.1/scons-3.1.1.tar.gz : 4cea417fdd7499a36f407923d03b4b7000b0f9e8fd7b31b316b9ce7eba9143a5
homepage   : https://scons.org/
license    : MIT
component  : programming.tools
summary    : Extensible Python-based build utility
description: |
    SCons is a python-based software construction tool. Think of SCons as an improved, cross-platform substitute for the classic Make utility with integrated functionality similar to autoconf/automake and compiler caches such as ccache. In short, SCons is an easier, more reliable and faster way to build software.
build      : |
    %python3_setup
install    : |
    %python3_install

    # Remove Windows scripts
    rm -f $installdir/usr/bin/scons*.bat
