name       : scons
version    : 4.4.0
release    : 11
source     :
    - https://github.com/scons/scons/archive/4.4.0.tar.gz : b4fef9df167b16b94a91bcc3905c595a5768a433f2aee9abe7f4fffac201eeaa
homepage   : https://scons.org/
license    : MIT
component  : programming.tools
summary    : Extensible Python-based build utility
description: |
    SCons is a python-based software construction tool. Think of SCons as an improved, cross-platform substitute for the classic Make utility with integrated functionality similar to autoconf/automake and compiler caches such as ccache. In short, SCons is an easier, more reliable and faster way to build software.
builddeps  :
    - python-wheel
build      : |
    python3 scripts/scons.py --include-dir= -j1
    %python3_setup
install    : |
    %python3_install --install-data=/usr/share/man/man1/
#check      : |
#    %python3_test runtest.py --all --unit-only
