name       : scons
version    : 3.1.2
release    : 7
source     :
    - https://sourceforge.net/projects/scons/files/scons/3.1.2/scons-3.1.2.tar.gz : 7801f3f62f654528e272df780be10c0e9337e897650b62ddcee9f39fde13f8fb
homepage   : https://scons.org/
license    : MIT
component  : programming.tools
summary    : Extensible Python-based build utility
description: |
    SCons is a python-based software construction tool. Think of SCons as an improved, cross-platform substitute for the classic Make utility with integrated functionality similar to autoconf/automake and compiler caches such as ccache. In short, SCons is an easier, more reliable and faster way to build software.
setup      : |
    sed -i -e "s|#! /usr/bin/env python|#! /usr/bin/env python3|g" script/*
build      : |
    %python3_setup
install    : |
    %python3_install
    install -dm00755 $installdir/usr/share
    mv $installdir/usr/man $installdir/usr/share/man

    # Remove Windows scripts
    rm -f $installdir/usr/bin/scons*.bat
