name       : scons
version    : 3.0.1
release    : 3
source     :
    - https://vorboss.dl.sourceforge.net/project/scons/scons/3.0.1/scons-3.0.1.tar.gz : 24475e38d39c19683bc88054524df018fe6949d70fbd4c69e298d39a0269f173
license    : MIT
component  : programming.tools
summary    : Extensible Python-based build utility
description: |
    Extensible Python-based build utility
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
